name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1.1.0  # works with yarn cache
    - run: yarn build
